In [16]:
import pandas as pd
import sklearn
import numpy as np

# importing of libraries

In [17]:
data = pd.read_csv(r"C:\Users\ADMIN\Downloads\May_26_-_Hands_on\churn.csv")


data.columns = data.columns.str.replace("'"," ")

# importing the dataset using pandas 

In [18]:
size=data.size
print(size)

# Finding the size of the dataset

69993


In [19]:
shape= data.shape
print(shape)

# Finding the shape of the dataset

(3333, 21)


In [20]:
data.head

# Printing some lines of the dataset

<bound method NDFrame.head of      State  Account Length  Area Code     Phone Int l Plan VMail Plan  \
0       KS             128        415  382-4657         no        yes   
1       OH             107        415  371-7191         no        yes   
2       NJ             137        415  358-1921         no         no   
3       OH              84        408  375-9999        yes         no   
4       OK              75        415  330-6626        yes         no   
5       AL             118        510  391-8027        yes         no   
6       MA             121        510  355-9993         no        yes   
7       MO             147        415  329-9001        yes         no   
8       LA             117        408  335-4719         no         no   
9       WV             141        415  330-8173        yes        yes   
10      IN              65        415  329-6603         no         no   
11      RI              74        415  344-9403         no         no   
12      IA           

In [21]:
data.columns

# Printing all the columns of the dataset

Index(['State', 'Account Length', 'Area Code', 'Phone', 'Int l Plan',
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls', 'Day Charge',
       'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins', 'Night Calls',
       'Night Charge', 'Intl Mins', 'Intl Calls', 'Intl Charge',
       'CustServ Calls', 'Churn?'],
      dtype='object')

In [22]:
data.describe

# Describing the dataset

<bound method NDFrame.describe of      State  Account Length  Area Code     Phone Int l Plan VMail Plan  \
0       KS             128        415  382-4657         no        yes   
1       OH             107        415  371-7191         no        yes   
2       NJ             137        415  358-1921         no         no   
3       OH              84        408  375-9999        yes         no   
4       OK              75        415  330-6626        yes         no   
5       AL             118        510  391-8027        yes         no   
6       MA             121        510  355-9993         no        yes   
7       MO             147        415  329-9001        yes         no   
8       LA             117        408  335-4719         no         no   
9       WV             141        415  330-8173        yes        yes   
10      IN              65        415  329-6603         no         no   
11      RI              74        415  344-9403         no         no   
12      IA       

In [23]:
data.head(3)

#Printing first 3 columns of dataset

State  Account Length  Area Code     Phone Int l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   

   VMail Message  Day Mins  Day Calls  Day Charge  ...  Eve Calls  Eve Charge  \
0             25     265.1        110       45.07  ...         99       16.78   
1             26     161.6        123       27.47  ...        103       16.62   
2              0     243.4        114       41.38  ...        110       10.30   

   Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  Intl Charge  \
0       244.7           91         11.01       10.0           3         2.70   
1       254.4          103         11.45       13.7           3         3.70   
2       162.6          104          7.32       12.2           5         3.29   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  

[3 rows x 21 columns]

In [24]:
target = data['Churn?']

# Finding the target column

In [25]:
print(target)

0       False.
1       False.
2       False.
3       False.
4       False.
5       False.
6       False.
7       False.
8       False.
9       False.
10       True.
11      False.
12      False.
13      False.
14      False.
15       True.
16      False.
17      False.
18      False.
19      False.
20      False.
21       True.
22      False.
23      False.
24      False.
25      False.
26      False.
27      False.
28      False.
29      False.
         ...  
3303    False.
3304     True.
3305    False.
3306    False.
3307    False.
3308    False.
3309    False.
3310    False.
3311    False.
3312    False.
3313    False.
3314    False.
3315    False.
3316    False.
3317    False.
3318    False.
3319    False.
3320     True.
3321    False.
3322     True.
3323     True.
3324    False.
3325    False.
3326    False.
3327    False.
3328    False.
3329    False.
3330    False.
3331    False.
3332    False.
Name: Churn?, Length: 3333, dtype: object


In [26]:
data = data.drop(["Account Length","Area Code","Phone","Churn?","State"],axis=1)

# Dropping the unnecessary columns

In [27]:
data.head

<bound method NDFrame.head of      Int l Plan VMail Plan  VMail Message  Day Mins  Day Calls  Day Charge  \
0            no        yes             25     265.1        110       45.07   
1            no        yes             26     161.6        123       27.47   
2            no         no              0     243.4        114       41.38   
3           yes         no              0     299.4         71       50.90   
4           yes         no              0     166.7        113       28.34   
5           yes         no              0     223.4         98       37.98   
6            no        yes             24     218.2         88       37.09   
7           yes         no              0     157.0         79       26.69   
8            no         no              0     184.5         97       31.37   
9           yes        yes             37     258.6         84       43.96   
10           no         no              0     129.1        137       21.95   
11           no         no        

In [28]:
categorical_data = data.iloc[:,[0,1]]
print(categorical_data)

# Finding the categorical data

     Int l Plan VMail Plan
0            no        yes
1            no        yes
2            no         no
3           yes         no
4           yes         no
5           yes         no
6            no        yes
7           yes         no
8            no         no
9           yes        yes
10           no         no
11           no         no
12           no         no
13           no         no
14           no         no
15           no         no
16           no        yes
17           no         no
18           no        yes
19           no         no
20           no         no
21           no         no
22           no         no
23           no         no
24           no         no
25           no         no
26           no        yes
27           no         no
28           no         no
29           no         no
...         ...        ...
3303         no        yes
3304        yes         no
3305         no        yes
3306         no        yes
3307         no         no
3

In [29]:
# All the categiorical data

In [30]:
from sklearn.preprocessing import LabelEncoder 
  
le = LabelEncoder() 
  
data['VMail Plan']= le.fit_transform(data['VMail Plan']) 
data['Int l Plan']= le.fit_transform(data['Int l Plan']) 

print(data['Int l Plan'])
print(data['VMail Plan'])

# Encoding the categorical data

0       0
1       0
2       0
3       1
4       1
5       1
6       0
7       1
8       0
9       1
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
3303    0
3304    1
3305    0
3306    0
3307    0
3308    0
3309    1
3310    0
3311    0
3312    0
3313    0
3314    0
3315    0
3316    0
3317    1
3318    0
3319    0
3320    1
3321    0
3322    0
3323    0
3324    0
3325    0
3326    0
3327    0
3328    0
3329    0
3330    0
3331    1
3332    0
Name: Int l Plan, Length: 3333, dtype: int32
0       1
1       1
2       0
3       0
4       0
5       0
6       1
7       0
8       0
9       1
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      1
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      1
27      0
28      0
29      0
       ..
3303    1
3304    0
3305    1
3306 

In [31]:
data.isnull().any()

# Finding the null values in the dataset

Int l Plan        False
VMail Plan        False
VMail Message     False
Day Mins          False
Day Calls         False
Day Charge        False
Eve Mins          False
Eve Calls         False
Eve Charge        False
Night Mins        False
Night Calls       False
Night Charge      False
Intl Mins         False
Intl Calls        False
Intl Charge       False
CustServ Calls    False
dtype: bool

In [32]:
#NO imputer needed as no null values found in the dataset

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.3)

# importing sklearn and splitting the data into train and test

In [34]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)

#Using the decision tree classifier

In [35]:
clf.fit(x_train,y_train)
pred=clf.predict(x_test)


In [36]:
from sklearn.metrics import accuracy_score
print(accuracy_score(pred ,y_test))

# Finding the accuracy of our model

0.901


In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

# Confusion Matrix for the model

array([[796,  46],
       [ 53, 105]], dtype=int64)

In [44]:
from sklearn import svm
clf = svm.SVC(kernel ='linear', C=0.025,random_state=0)
clf.fit(x_train,y_train)

# Support Vector Machines

SVC(C=0.025, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [45]:
pred=clf.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(pred ,y_test))

# Accuracy

0.861


In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[861,   0],
       [139,   0]], dtype=int64)

In [41]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.3)

clf = RandomForestClassifier(max_depth=5,n_estimators=10 ,max_features=10, random_state=0)
clf.fit(x_train,y_train)

print(clf.predict(x_test))
print(accuracy_score(pred ,y_test))

# Random Forest

['False.' 'True.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'True.' 'False.'
 'True.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'True.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'False.' 'True.' 'False.' 'False.' 'True.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'True.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'True.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'True.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'True.' 'False.' 'False.'
 'False.' 'False.' 'True.' 'False.' 'False.' 'False.' 'False.' 'False.'
 'False.' 'False.' 'False.' 'False.' 'False.' 'False.' 'False.

In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(pred ,y_test))

0.861


In [43]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[861,   0],
       [139,   0]], dtype=int64)